modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/HudCompass/issues"

[[mods]]
modId="hudcompass"
version="${file.jarVersion}"
displayName="HUD Compass"
logoFile="logo.png"
authors="gigaherz"
displayURL="https://github.com/gigaherz/HudCompass"
description='''
See where you go
'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.hudcompass]]
   modId="neoforge"
   type="required"
   versionRange="[21.0.42-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="journeymap_api"
   type="optional"
   versionRange="[2.0.0,)"
   ordering="NONE"
   side="BOTH"
