@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.hudcompass.integrations.journeymap;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;