@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.hudcompass.waypoints;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;