@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.hudcompass.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;