@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.hudcompass;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;