@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.hudcompass.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;